### ISSUE TITLE
[Bug]: Constant reconnecting - mail spam from panasonic

### ISSUE THREAD

**Issue by aLAN-LDZ** [cjaliaga/home-assistant-aquarea#119]
### The problem

![image](https://github.com/user-attachments/assets/0e80829a-b061-4d11-b76c-0c4f529d16e0)

Hey, I've already received a thousand emails from Panasonic. That thanks for connecting. A few emails per minute.

I understand that this is a problem on our side and there are many reconnections every few seconds?

### What version of Home Assistant Core are you running?

latest

### What type of installation are you running?

Home Assistant Container

### What version of the integration are you running?

latest

### Device description

heat pump, one zone

### Is the integration loading?

Yes

### Is the adapter able to connect to the Aquarea Smart Cloud with a stable internet connection?

Yes

### Are you able to perform the action you're trying to with the Aquarea Smart Cloud Site/App?

Yes

**Comment by mkozar87** [comment]
Im facing the same issue. It started around 2h ago.

**Comment by roelofz** [comment]
Same here, tried upgrade of the integration (was still at 0.70, reset the app and now not able to authenticate with Panasonic.
So username / pw was wrong, looking at the integration feedback and a successful login was mentioned by email.

**Comment by as9441** [comment]
I have the same, I enter the correct password in HA and I get the information - unknown error.

**Comment by wpatrik14** [comment]
Same here

**Comment by ddanielczyk** [comment]
Same

**Comment by compala** [comment]
Same

**Comment by tson0n0** [comment]
same problem here.
Panasonic changed again the authentification ?

**Comment by MarkMikkelsen83** [comment]
Same

**Comment by amaretto4u** [comment]
same problem

**Comment by uldiseihenbergs** [comment]
same problem for me too.
2FA from panasonic enabled by default now? so no idea how to connect from integration..

**Comment by GermanCaruncho** [comment]
In my case, after 256 emails :P''' and the automation inexplicably stopped working, I entered the link and authenticated. Magically it has come back to life. Panasonic has made the mistake of touching something that works, it seems. (this is the first degree in computer science)

**Comment by jsole** [comment]
Same here, I deactivated the integration to stop reciving emails. I loged in with my computer, reactivated the integration and it's working again... I'm thinking to migrate to heishamon to avoid all this random problems.

**Comment by jaypikay** [comment]
Logging in at aquarea-smart.panasonic.com actually resolved the issue for me, too.

**Comment by raeserfisk** [comment]
Maybe we shouldnt make something out of nothing here guys? Just as @jaypikay stated above the problem is solved by login to aquarea-smart.panasonic.com and accepting the new user agreement.

Until further notice I would suggest that this issue is considered solved with the above solution.

**Comment by roelofz** [comment]
It looks Panasonic was having a problem, I did login on the website earlier today, and this did not fix it. 
Now it works again, so this issue can be closed!

**Comment by uldiseihenbergs** [comment]
for me it's working too now. Email spam continues, but luckily not at that very high rate..

**Comment by cjaliaga** [comment]
Thanks everyone for the reports. It looked indeed an issue on the Aquarea platform/Panasonic Auth Service.
